[[headers]]
  for = "/fonts/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000" # 1 year

[[headers]]
  for = "/images/*"
    [headers.values]
    Cache-Control = "public, max-age=604800" # 1 week
